// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'backbone.offline', 'models/article'], function(_, Backbone, Offline, Article) {
    App.Collections.Articles = (function(_super) {
      __extends(Articles, _super);

      function Articles() {
        return Articles.__super__.constructor.apply(this, arguments);
      }

      Articles.prototype.url = '/api/articles';

      Articles.prototype.model = Article;

      Articles.prototype.initialize = function() {
        return this.storage = new Offline.Storage('article', this);
      };

      return Articles;

    })(Backbone.Collection);
    return App.Collections.Articles;
  });

}).call(this);

//# sourceMappingURL=Articles.map
