// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'models/article'], function(_, Backbone, Model) {
    App.Collections.Article = (function(_super) {
      __extends(Article, _super);

      function Article() {
        return Article.__super__.constructor.apply(this, arguments);
      }

      Article.prototype.url = '/api/articles';

      Article.prototype.model = Model;

      Article.prototype.initialize = function() {};

      return Article;

    })(Backbone.Collection);
    return App.Collections.Article;
  });

}).call(this);

//# sourceMappingURL=Article.map
