// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone'], function(_, Backbone) {
    App.Models.Article = (function(_super) {
      __extends(Article, _super);

      function Article() {
        return Article.__super__.constructor.apply(this, arguments);
      }

      Article.prototype["default"] = {
        _id: '',
        title: ''
      };

      Article.prototype.url = '/api/article';

      Article.prototype.idAttribute = '_id';

      Article.prototype.initialize = function() {
        return this.on('change', function() {
          return this.updated_at = new Date();
        }, this);
      };

      return Article;

    })(Backbone.Model);
    return App.Models.Article;
  });

}).call(this);

//# sourceMappingURL=Article.map
