// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery.mockjax', 'underscore'], function(mockjax, _) {
    App.Mocks.Album = (function() {
      function Album() {}

      Album.prototype.getId = function() {
        return _.uniqueId();
      };

      Album.prototype.dataAll = function() {
        return [
          {
            '_id': this.getId(),
            'title': 'title 123',
            'age': '1234'
          }, {
            '_id': this.getId(),
            'title': 'title 123',
            'age': '1234'
          }
        ];
      };

      Album.prototype.article = function() {
        $.mockjax({
          url: '/api/article',
          responseTime: 200,
          contentType: 'text/json',
          responseText: {
            '_id': this.getId(),
            'title': 'title 15',
            "age": 37
          }
        });
        return $.mockjax({
          url: '/api/articles',
          responseTime: 200,
          contentType: 'text/json',
          responseText: this.dataAll()
        });
      };

      return Album;

    })();
    return App.Mocks.Album;
  });

}).call(this);

//# sourceMappingURL=Album.map
