// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery.mockjax'], function() {
    App.Applications.Mockjax = (function() {
      function Mockjax() {}

      Mockjax.prototype.article = function() {
        return $.mockjax({
          url: '/api/article',
          responseTime: 200,
          contentType: 'text/json',
          responseText: {
            "_id": 1,
            "title": "xxxx",
            "age": 28
          }
        });
      };

      Mockjax.prototype.articles = function() {
        return $.mockjax({
          url: '/api/articles',
          responseTime: 200,
          contentType: 'text/json',
          responseText: [
            {
              "_id": 1,
              "title": "xxxx",
              "age": 28
            }, {
              "_id": 2,
              "title": "yyyyy",
              "age": 39
            }
          ]
        });
      };

      return Mockjax;

    })();
    return App.Applications.Mockjax;
  });

}).call(this);

//# sourceMappingURL=mockjax.map
