// Generated by CoffeeScript 1.7.1
(function() {
  require(['config'], function() {
    return require(['models/Article', 'collections/Article', 'views/Article', 'mocks/Article', 'underscore', 'TweenMax', 'TimelineMax', 'jquery'], function(Model, Collection, View, Mocks, _, TweenMax, TimelineMax, $) {
      var article, articles, mock, view;
      mock = new Mocks();
      mock.article();
      article = new Model();
      article.save({
        title: 'title 14'
      }, {
        success: function(d) {
          return console.log(d);
        }
      });
      articles = new Collection();
      view = new View({
        el: '#xxx'
      });
      return articles.fetch({
        success: function(d) {
          var t;
          view.list(d);
          t = new TimelineMax();
          return t.add(TweenMax.to($('.logo'), .5, {
            marginLeft: "50px",
            ease: Bounce.easeParams
          }));
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=intro.map
