// Generated by CoffeeScript 1.7.1
(function() {
  require(['config'], function() {
    return require(['models/Article', 'collections/Article', 'views/Article', 'mocks/Article', 'underscore'], function(Model, Collection, View, Mocks, _) {
      var article, articles, mock, view;
      mock = new Mocks();
      mock.article();
      article = new Model();
      article.save({
        title: 'title 14'
      }, {
        success: function(d) {
          return console.log(d);
        }
      });
      articles = new Collection();
      view = new View({
        el: '#xxx'
      });
      return articles.fetch({
        success: function(d) {
          return view.list(d);
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=intro.map
